# Generated by Django 4.2.4 on 2023-10-12 20:13

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algoritmo',
            fields=[
                ('algoritmo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('abrebiatura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('diagnostico_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoImagen',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False)),
                ('probabilidad_cancer', models.FloatField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='MetricasDesempeno',
            fields=[
                ('metrica_id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('precision', models.FloatField()),
                ('sensibilidad', models.FloatField()),
                ('especificidad', models.FloatField()),
                ('exactitud', models.FloatField()),
                ('datos_entrenados', models.PositiveIntegerField()),
                ('algoritmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.algoritmo')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.image_path)),
                ('tipo_imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoimagen')),
            ],
        ),
    ]
