# Generated by Django 4.2.5 on 2023-10-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricasdesempeno',
            name='ssim',
        ),
        migrations.AlterField(
            model_name='metricasdesempeno',
            name='especificidad',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metricasdesempeno',
            name='exactitud',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metricasdesempeno',
            name='precision',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metricasdesempeno',
            name='sensibilidad',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
