# Generated by Django 4.2.5 on 2023-10-16 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoimagen',
            name='diagnostico_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.diagnostico'),
            preserve_default=False,
        ),
    ]
