# Generated by Django 4.2.5 on 2023-10-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tipoimagen_diagnostico_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoimagen',
            old_name='diagnostico_id',
            new_name='diagnostico',
        ),
    ]
