# Generated by Django 4.2.5 on 2023-10-17 17:53

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_metricasdesempeno_ssim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='resultado',
            name='imagen_analizada',
            field=models.ImageField(default='', upload_to=api.models.image_path2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado',
            name='probabilidad_cancer',
            field=models.FloatField(default=0),
        ),
    ]
