# Generated by Django 4.2.4 on 2023-10-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resultado_fecha_resultado_imagen_analizada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('loss', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('val_loss', models.FloatField()),
                ('val_accuracy', models.FloatField()),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entrenamiento')),
            ],
        ),
    ]
